[project]
name = "gamecraft-alt-controller-jam-board"
version = "0.1.0"
description = "Gamecraft Alt-Controller-Jam 2023 Code"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [
    { name = "Michael Twomey", email = "mick@twomeylee.name" }
]
requires-python = ">=3.6"
dependencies = [
    "adafruit-circuitpython-debouncer>=2.0.15",
    "adafruit-circuitpython-hid>=6.0.1",
    "community-circuitpython-tca9555>=0.2.2",
]

[project.urls]
Homepage = "https://github.com/micktwomey/alt-controller-jam"
Repository = "https://github.com/micktwomey/alt-controller-jam"


[build-system]
requires = ["uv_build>=0.11.29,<0.12.0"]
build-backend = "uv_build"
