M48
; DRILL file {KiCad 7.0.7} date 2023 September 10, Sunday 22:48:24
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-09-10T22:48:24+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0157
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0315
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
%
G90
G05
T1
X2.9528Y-2.874
T2
X2.4528Y-3.4252
X2.9528Y-3.4252
T3
X1.7717Y-3.3465
X1.7717Y-3.4465
T0
M30
